### ISSUE TITLE
Get agent traces in a file

### ISSUE THREAD

**Issue by aloussase** [grafana/quickpizza#210]
Hello,

I am trying to get the traces emitted by the application in a file.

I know for example with the OTEL collector, one can configure a file exporter for this purpose: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/fileexporter/README.md.

How can we do this with Grafana agent?

Many thanks.

**Comment by aloussase** [comment]
I found the place where Tempo stores traces locally. This is in the local compose config:
```yml
  tempo:
    image: grafana/tempo:2.1.0
    command:
      - "-storage.trace.backend=local" # tell tempo where to permanently put traces
      - "-storage.trace.local.path=/tmp/tempo/traces"
      - "-storage.trace.wal.path=/tmp/tempo/wal" # tell tempo where to store the wal
      - "-auth.enabled=false" # disables the requirement for the X-Scope-OrgID header
      - "-server.http-listen-port=3200"
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
```
We can just mount `/tmp/tempo/traces` on the local filesystem.

I also found this:
```river
otelcol.exporter.otlp "default" {
  client {
    // TODO: Replace this with the endpoint for your trace receiver
    endpoint = env("TRACES_ENDPOINT")
    tls {
        insecure             = true
        insecure_skip_verify = true
    }
  }
}
```
Which defaults to Tempo, but could be change to the OTEL collector for example.
